In [55]:
import pandas as pd


data=pd.read_csv('train_fwYjLYX.csv')
df=pd.DataFrame(data)
print(data.columns)
print(df['state'])


Index(['application_date', 'segment', 'branch_id', 'state', 'zone',
       'case_count'],
      dtype='object')
0        WEST BENGAL
1        WEST BENGAL
2        WEST BENGAL
3        WEST BENGAL
4        WEST BENGAL
            ...     
80397    WEST BENGAL
80398    WEST BENGAL
80399    WEST BENGAL
80400    WEST BENGAL
80401    WEST BENGAL
Name: state, Length: 80402, dtype: object


In [58]:
from sklearn.utils import shuffle
#df=df.drop(['state','zone'],axis=1)
x,y=shuffle(x,y,random_state=10)
print(x)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#df.state = le.fit_transform(df.state)
df.application_date = le.fit_transform(df.application_date)
x=df[df.columns[:3]].values
y=df[df.columns[3]].values
df['branch_id'] = df['branch_id'].replace(np.nan, 0)
df=df.astype({"branch_id": int})
print(df.dtypes)
print(y)

[[822.   1.  73.]
 [682.   1.  82.]
 [478.   1. 249.]
 ...
 [ 51.   1.  17.]
 [245.   1.  16.]
 [745.   1. 248.]]
application_date    int64
segment             int64
branch_id           int32
case_count          int64
dtype: object
[  40    5    4 ... 1028 1946 1984]


In [59]:
x_test = pd.read_csv('test_1eLl9Yf.csv')
print(x_test.head)
print(x_test.dtypes)

<bound method NDFrame.head of       id application_date  segment
0      1       06-07-2019        1
1      2       07-07-2019        1
2      3       08-07-2019        1
3      4       09-07-2019        1
4      5       10-07-2019        1
..   ...              ...      ...
175  176       20-10-2019        2
176  177       21-10-2019        2
177  178       22-10-2019        2
178  179       23-10-2019        2
179  180       24-10-2019        2

[180 rows x 3 columns]>
id                   int64
application_date    object
segment              int64
dtype: object


In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_squared_error,mean_absolute_error

model=LinearRegression()
model=model.fit(x,y)
y_pred=model.predict()
#compute the RMSE of our predictions
print("MAE is",mean_absolute_error(y_pred,test_target))
print("MSE is ",mean_squared_error(y_pred,test_target))
#print("RMSE is",np.sqrt(mean_squared_error(y_pred,test_target))